# Generated by Django 3.0.1 on 2020-02-15 19:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('stopped', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 2, 15, 22, 3, 17, 362109))),
                ('date_started', models.DateTimeField(default=datetime.datetime(2020, 2, 15, 22, 3, 17, 362109))),
                ('date_stopped', models.DateTimeField(default=datetime.datetime(2020, 2, 15, 22, 3, 17, 362109))),
                ('turn_period', models.IntegerField(default=0)),
                ('team_count', models.IntegerField(default=0)),
                ('user_lowest_level', models.IntegerField(default=-1)),
                ('user_highest_level', models.IntegerField(default=-1)),
                ('winning_team', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated', models.BooleanField(default=False)),
                ('victories_count', models.IntegerField(default=0)),
                ('played_games_count', models.IntegerField(default=0)),
                ('team', models.IntegerField(default=0)),
                ('extra_info', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PressureToolSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('type', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSessionInvolvementFact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GameSession')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
