# Generated by Django 3.0.1 on 2020-03-30 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='started',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='stopped',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='team_count',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='money_limit',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='phase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='turn_of_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='user_limit',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='userdata',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 12, 11, 30, 581607)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 12, 11, 30, 581607)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_stopped',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 30, 12, 11, 30, 581607)),
        ),
        migrations.DeleteModel(
            name='GameSessionInvolvementFact',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GameSession'),
        ),
    ]
