# Generated by Django 3.0.1 on 2020-02-16 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='coins_per_hour',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 12, 51, 54, 731053)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 12, 51, 54, 731053)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_stopped',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 16, 12, 51, 54, 731053)),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='coins',
            field=models.IntegerField(default=42),
        ),
    ]
