# Generated by Django 3.0.5 on 2020-05-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstats',
            name='coins',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
