# Generated by Django 3.0.4 on 2020-06-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200530_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='reputation',
        ),
    ]
