# Generated by Django 3.0.4 on 2020-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userdata_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='user_highest_level',
            field=models.IntegerField(default=65535),
        ),
    ]
