# Generated by Django 3.0.4 on 2020-06-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200602_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='turn_of_team',
        ),
    ]
