# Generated by Django 3.0.4 on 2020-06-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gamesession_turn_of_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamStats',
        ),
    ]
