# Generated by Django 3.0.1 on 2020-03-07 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200306_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='started',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='stopped',
        ),
        migrations.RemoveField(
            model_name='gamesession',
            name='team_count',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='phase',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='turn_of_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='user_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userdata',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 18, 7, 43, 276428)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 18, 7, 43, 276428)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_stopped',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 7, 18, 7, 43, 276428)),
        ),
        migrations.DeleteModel(
            name='GameSessionInvolvementFact',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
