# Generated by Django 3.0.1 on 2020-04-04 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200320_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=42)),
            ],
        ),
        migrations.AddField(
            model_name='gamesession',
            name='money_limit',
            field=models.IntegerField(default=255),
        ),
        migrations.AddField(
            model_name='userdata',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 19, 3, 34, 938113)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_started',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 19, 3, 34, 938134)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='date_stopped',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 19, 3, 34, 938146)),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='user_limit',
            field=models.IntegerField(default=6),
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
        migrations.AddField(
            model_name='teamstats',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.GameSession'),
        ),
    ]
