# Generated by Django 3.0.1 on 2020-02-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200216_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesessioninvolvementfact',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='gamesessioninvolvementfact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pressuretoolset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='user',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.DeleteModel(
            name='GameSessionInvolvementFact',
        ),
        migrations.DeleteModel(
            name='PressureToolSet',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
